### PR TITLE
 Fix incorrect function name for bit array add byte reversed

### PR DESCRIPTION
**Pull request by Ericwhh**

### CODE REVIEW

**Comment by KarelChanivecky** [comment]
Guys we should avoid changing our function names. We may regret our identifiers, but some people may already depend on the given API. At some point we could do a complete revamp of this library and release it as a new version, then we could have new identifiers.

**Comment by Ericwhh** [comment]
> Guys we should avoid changing our function names. We may regret our identifiers, but some people may already depend on the given API. At some point we could do a complete revamp of this library and release it as a new version, then we could have new identifiers.

The issue was not about regretting identifiers. The source file and header file did not match for that function name, meaning the function in this library was unusable.

**Comment by KarelChanivecky** [comment]
I stand corrected

**Comment by KarelChanivecky** [comment]
Let's try leaving more comments for each other when making pull requests then

**Pull request merged**
